export default [
    {
        id: 1,
        boardId: 2,
        name: 'c cezczecezc',
        type: 'Bug',
        status: 'Done',
        projectId: '1',
    },
    {
        id: 1,
        boardId: 2,
        name: 'zcezc cezczecezc',
        type: 'Bug',
        status: 'Todo',
        projectId: '2',
    },
    {
        id: 1,
        boardId: 2,
        name: 'aezcezcezcezc cezczecezc',
        type: 'Feature',
        status: 'Done',
        projectId: '1',
    },
    {
        id: 1,
        boardId: 2,
        name: 'cezczecezc',
        type: 'Feature',
        status: 'Todo',
        projectId: '2',
    },
    {
        id: 1,
        boardId: 2,
        name: 'czec ezcezcezcezc cezczecezc',
        type: 'Bug',
        status: 'Done',
        projectId: '1',
    },
]
